/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/sync/stream': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Stream sync changes
     * @description #### Controller:
     *
     *     `github.com/MaroonRides/api/apps/gateway/controllers.(*SyncController).stream`
     *
     *     #### Middlewares:
     *
     *     - `github.com/MaroonRides/api/apps/gateway/controllers.gzipped`
     *
     *     ---
     *
     *     Streams every change after the given acks as JSON lines. Each line is one SyncStreamLine.
     */
    post: operations['syncStream'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/version/supported': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get the minimum supported version that the server supports communicating with
     * @description #### Controller:
     *
     *     `github.com/MaroonRides/api/apps/gateway/controllers.(*VersionController).supportedVersion`
     *
     *     ---
     */
    get: operations['getSupportedVersion'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AlertDeleteV1Line: {
      ack: string;
      data: components['schemas']['SyncAlertDeleteV1'];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'AlertDeleteV1';
    };
    AlertDirectionDeleteV1Line: {
      ack: string;
      data: components['schemas']['SyncAlertDirectionDeleteV1'];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'AlertDirectionDeleteV1';
    };
    AlertDirectionV1Line: {
      ack: string;
      data: components['schemas']['SyncAlertDirectionV1'];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'AlertDirectionV1';
    };
    AlertV1Line: {
      ack: string;
      data: components['schemas']['SyncAlertV1'];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'AlertV1';
    };
    DirectionDeleteV1Line: {
      ack: string;
      data: components['schemas']['SyncDirectionDeleteV1'];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'DirectionDeleteV1';
    };
    DirectionV1Line: {
      ack: string;
      data: components['schemas']['SyncDirectionV1'];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'DirectionV1';
    };
    ErrorItem: {
      /** @description Additional information about the error */
      more?: {
        [key: string]: unknown;
      } | null;
      /** @description For example, name of the parameter that caused the error */
      name: string;
      /** @description Human readable error message */
      reason: string;
    };
    /** @description HTTPError schema */
    HTTPError: {
      /** @description Human readable error message */
      detail?: string;
      errors?: components['schemas']['ErrorItem'][] | null;
      instance?: string;
      /**
       * @description HTTP status code
       * @example 403
       */
      status?: number;
      /** @description Short title of the error */
      title?: string;
      /** @description URL of the error type. Can be used to lookup the error in a documentation */
      type?: string;
    };
    RouteDeleteV1Line: {
      ack: string;
      data: components['schemas']['SyncRouteDeleteV1'];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'RouteDeleteV1';
    };
    RouteV1Line: {
      ack: string;
      data: components['schemas']['SyncRouteV1'];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'RouteV1';
    };
    StopDeleteV1Line: {
      ack: string;
      data: components['schemas']['SyncStopDeleteV1'];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'StopDeleteV1';
    };
    StopV1Line: {
      ack: string;
      data: components['schemas']['SyncStopV1'];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'StopV1';
    };
    /** @description SupportedVersionResponse schema */
    SupportedVersionResponse: {
      version: string;
    };
    /** @description SyncAlertDeleteV1 schema */
    SyncAlertDeleteV1: {
      /** Format: uuid */
      alertId: string;
    };
    /** @description SyncAlertDirectionDeleteV1 schema */
    SyncAlertDirectionDeleteV1: {
      /** Format: uuid */
      alertDirectionId: string;
    };
    /** @description SyncAlertDirectionV1 schema */
    SyncAlertDirectionV1: {
      /** Format: uuid */
      alertId: string;
      /** Format: uuid */
      directionId: string;
      /** Format: uuid */
      id: string;
    };
    /** @description SyncAlertV1 schema */
    SyncAlertV1: {
      dailyEndTime: string;
      dailyStartTime: string;
      description: string;
      /** Format: date-time */
      endsAt: string | null;
      /** Format: uuid */
      id: string;
      /** Format: date-time */
      startsAt: string;
      timeRangeText: string;
      title: string;
    };
    /** @description SyncCompleteV1 schema */
    SyncCompleteV1: unknown;
    SyncCompleteV1Line: {
      ack: string;
      data: components['schemas']['SyncCompleteV1'];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'SyncCompleteV1';
    };
    /** @description SyncDirectionDeleteV1 schema */
    SyncDirectionDeleteV1: {
      /** Format: uuid */
      directionId: string;
    };
    /** @description SyncDirectionV1 schema */
    SyncDirectionV1: {
      destination: string;
      /** Format: uuid */
      id: string;
      path: string;
      /** Format: uuid */
      routeId: string;
      sequence: number;
    };
    /**
     * SyncEntityType
     * @description SyncEntityType schema
     * @enum {string}
     */
    SyncEntityType:
      | 'RouteV1'
      | 'RouteDeleteV1'
      | 'DirectionV1'
      | 'DirectionDeleteV1'
      | 'StopV1'
      | 'StopDeleteV1'
      | 'AlertV1'
      | 'AlertDeleteV1'
      | 'AlertDirectionV1'
      | 'AlertDirectionDeleteV1'
      | 'TimetableV1'
      | 'TimetableDeleteV1'
      | 'SyncResetV1'
      | 'SyncCompleteV1';
    /** @enum {integer} */
    SyncProtocolVersion: 1;
    /** @description SyncRequest schema */
    SyncRequest: {
      acks: string[] | null;
      protocol: components['schemas']['SyncProtocolVersion'];
      types: components['schemas']['SyncRequestType'][] | null;
    };
    /** @enum {string} */
    SyncRequestType:
      | 'RoutesV1'
      | 'DirectionsV1'
      | 'StopsV1'
      | 'AlertsV1'
      | 'AlertDirectionsV1'
      | 'TimetablesV1';
    /** @description SyncResetV1 schema */
    SyncResetV1: unknown;
    SyncResetV1Line: {
      ack: string;
      data: components['schemas']['SyncResetV1'];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'SyncResetV1';
    };
    /** @description SyncRouteDeleteV1 schema */
    SyncRouteDeleteV1: {
      /** Format: uuid */
      routeId: string;
    };
    /** @description SyncRouteV1 schema */
    SyncRouteV1: {
      active: boolean;
      darkColor: string;
      /** Format: uuid */
      id: string;
      lightColor: string;
      longName: string;
      shortName: string;
    };
    /** @description SyncStopDeleteV1 schema */
    SyncStopDeleteV1: {
      /** Format: uuid */
      stopId: string;
    };
    /** @description SyncStopV1 schema */
    SyncStopV1: {
      amenities: string[] | null;
      /** Format: uuid */
      directionId: string;
      /** Format: uuid */
      id: string;
      isTimepoint: boolean;
      /** Format: double */
      lat: number;
      /** Format: double */
      lon: number;
      name: string;
      sequence: number;
    };
    SyncStreamLine:
      | components['schemas']['RouteV1Line']
      | components['schemas']['RouteDeleteV1Line']
      | components['schemas']['DirectionV1Line']
      | components['schemas']['DirectionDeleteV1Line']
      | components['schemas']['StopV1Line']
      | components['schemas']['StopDeleteV1Line']
      | components['schemas']['AlertV1Line']
      | components['schemas']['AlertDeleteV1Line']
      | components['schemas']['AlertDirectionV1Line']
      | components['schemas']['AlertDirectionDeleteV1Line']
      | components['schemas']['TimetableV1Line']
      | components['schemas']['TimetableDeleteV1Line']
      | components['schemas']['SyncResetV1Line']
      | components['schemas']['SyncCompleteV1Line'];
    /** @description SyncTimetableDeleteV1 schema */
    SyncTimetableDeleteV1: {
      /** Format: uuid */
      timetableId: string;
    };
    /** @description SyncTimetableV1 schema */
    SyncTimetableV1: {
      departures: string[] | null;
      /** Format: uuid */
      id: string;
      /** Format: date */
      serviceDate: string;
      /** Format: uuid */
      stopId: string;
    };
    TimetableDeleteV1Line: {
      ack: string;
      data: components['schemas']['SyncTimetableDeleteV1'];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'TimetableDeleteV1';
    };
    TimetableV1Line: {
      ack: string;
      data: components['schemas']['SyncTimetableV1'];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'TimetableV1';
    };
    /** @description unknown-interface schema */
    'unknown-interface': unknown;
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  syncStream: {
    parameters: {
      query?: never;
      header?: {
        Accept?: string;
      };
      path?: never;
      cookie?: never;
    };
    /** @description Request body for dtos.SyncRequest */
    requestBody: {
      content: {
        'application/json': components['schemas']['SyncRequest'];
      };
    };
    responses: {
      /** @description One SyncStreamLine per line */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/jsonlines+json': components['schemas']['SyncStreamLine'];
        };
      };
      /** @description Bad Request _(validation or deserialization error)_ */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPError'];
          'application/xml': components['schemas']['HTTPError'];
        };
      };
      /** @description Internal Server Error _(panics)_ */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPError'];
          'application/xml': components['schemas']['HTTPError'];
        };
      };
    };
  };
  getSupportedVersion: {
    parameters: {
      query?: never;
      header?: {
        Accept?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SupportedVersionResponse'];
        };
      };
      /** @description Bad Request _(validation or deserialization error)_ */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPError'];
          'application/xml': components['schemas']['HTTPError'];
        };
      };
      /** @description Internal Server Error _(panics)_ */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPError'];
          'application/xml': components['schemas']['HTTPError'];
        };
      };
    };
  };
}
