packages:
  - '*'

publicHoistPattern:
  - '*expo-modules-autolinking'
  - '*expo-modules-core'
  - '*babel-preset-expo'

allowBuilds:
  '@sentry/cli': true
  unrs-resolver: true

onlyBuiltDependencies:
  - unrs-resolver
