# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

# use changelog env var if set, otherwise use default
CHANGELOG = ENV['CHANGELOG'] || "Howdy! This update includes some bug fixes and performance improvements. Please let us know if you have any feedback or questions through TestFlight! Thanks and Gig 'Em!"

platform :ios do
  desc "Setup generated Xcode project for build"
  lane :prebuild do

    ASC_KEY_ID = ENV['ASC_KEY_ID']
    ASC_ISSUER_ID = ENV['ASC_ISSUER_ID']
    ASC_KEY_BASE64 = ENV['ASC_KEY_BASE64']
    TEAM_ID = ENV['TEAM_ID']

    # setup app store connect api key on local machine 
    app_store_connect_api_key(
      key_id: ASC_KEY_ID,
      issuer_id: ASC_ISSUER_ID,
      key_content: ASC_KEY_BASE64,
      is_key_content_base64: true
    )

    match(
      type: 'development',
      app_identifier: 'com.bwees.reveille-rides',
      readonly: true,
      git_basic_authorization: Base64.strict_encode64(ENV["GIT_AUTHORIZATION"])
    )

    match(
      type: 'appstore',
      app_identifier: 'com.bwees.reveille-rides',
      readonly: true,
      git_basic_authorization: Base64.strict_encode64(ENV["GIT_AUTHORIZATION"])
    )
    
    update_project_team(
      path: "ios/MaroonRides.xcodeproj",
      teamid: TEAM_ID
    )

    update_project_provisioning(
      xcodeproj: "ios/MaroonRides.xcodeproj",
      profile: ENV["sigh_com.bwees.reveille-rides_appstore_profile-path"],
      build_configuration: "Release",
      target_filter: "MaroonRides",
    )

    update_code_signing_settings(
      use_automatic_signing: false,
      path: "ios/MaroonRides.xcodeproj",
      team_id: TEAM_ID,
      bundle_identifier: "com.bwees.reveille-rides",
      code_sign_identity: "iPhone Distribution",
      sdk: "iphoneos*",
    )

    # set ITSAppUsesNonExemptEncryption to false, prevents Missing Compliance error in TF
    set_info_plist_value(
      path: "ios/MaroonRides/Info.plist",
      key: "ITSAppUsesNonExemptEncryption",
      value: false
    )
  end
  
  desc "Push a new build to TestFlight"
  lane :build do
    prebuild
    
    increment_build_number(xcodeproj: "ios/MaroonRides.xcodeproj", build_number: app_store_build_number(live: false) + 1)
    
    build_app(workspace: "ios/MaroonRides.xcworkspace", scheme: "MaroonRides")
    
    upload_to_testflight(
      notify_external_testers: true,
      changelog: CHANGELOG,
      groups: [
        "Beta Tester"
      ]
    )
  end
end

# fastlane/Fastfile
default_platform(:android)

platform :android do
  desc "Build APK with Gradle"
  lane :build_apk do
    gradle(
      task: "assemble",
      build_type: "Release",
      project_dir: "android/",
      flags: "--no-daemon"
    )
  end

  desc "Push a new build to Google Play Store"
  lane :build do
    build_apk

    upload_to_play_store(
      track: 'internal', 
      apk: './android/app/build/outputs/apk/release/app-release.apk',
      json_key_data: Base64.decode64(ENV['GOOGLE_PLAY_KEY']),
      package_name: ENV['PACKAGE_NAME']
    )
  end


end