default_platform(:ios)

IOS_APP_IDENTIFIER = 'com.bwees.reveille-rides'
WATCH_APP_IDENTIFIER = 'com.bwees.reveille-rides.watch'
XCODE_PROJECT = 'ios/App/App.xcodeproj'

CHANGELOG = ENV['CHANGELOG'] || "Howdy! This update includes some bug fixes and performance improvements. Please let us know if you have any feedback or questions through TestFlight! Thanks and Gig 'Em!"

PACKAGE_JSON = File.expand_path('../package.json', FastlaneCore::FastlaneFolder.path)
APP_VERSION = JSON.parse(File.read(PACKAGE_JSON))['version']

platform :ios do
  desc 'Push a new build to TestFlight'
  lane :build do
    setup_ci if ENV['CI']

    app_store_connect_api_key(
      key_id: ENV['ASC_KEY_ID'],
      issuer_id: ENV['ASC_ISSUER_ID'],
      key_content: ENV['ASC_KEY_BASE64'],
      is_key_content_base64: true,
    )

    match(
      type: 'appstore',
      app_identifier: [IOS_APP_IDENTIFIER, WATCH_APP_IDENTIFIER],
      readonly: true,
      git_basic_authorization: Base64.strict_encode64(ENV['GIT_AUTHORIZATION']),
    )

    build_number = app_store_build_number(live: false) + 1
    UI.message("Building #{APP_VERSION} (#{build_number})")

    build_app(
      project: XCODE_PROJECT,
      scheme: 'App',
      xcargs: "MARKETING_VERSION=#{APP_VERSION} CURRENT_PROJECT_VERSION=#{build_number}",
      export_options: {
        signing_style: 'manual',
        provisioningProfiles: {
          IOS_APP_IDENTIFIER => "match AppStore #{IOS_APP_IDENTIFIER}",
          WATCH_APP_IDENTIFIER => "match AppStore #{WATCH_APP_IDENTIFIER}",
        },
      },
    )

    upload_to_testflight(
      notify_external_testers: true,
      changelog: CHANGELOG,
      groups: ['Beta Tester'],
    )
  end
end

platform :android do
  desc 'Build a release App Bundle'
  lane :build do
    latest_version_code = google_play_track_version_codes(
      track: 'internal',
      json_key_data: Base64.decode64(ENV['GOOGLE_PLAY_KEY']),
      package_name: ENV['PACKAGE_NAME'],
    ).max || 1

    version_code = latest_version_code + 1
    UI.message("Building #{APP_VERSION} (#{version_code})")

    gradle(
      task: 'bundle',
      build_type: 'Release',
      project_dir: 'android/',
      flags: '--no-daemon',
      properties: {
        'versionCode' => version_code,
        'android.injected.signing.store.file' => ENV['KEY_PATH'],
        'android.injected.signing.store.password' => ENV['STORE_PASSWORD'],
        'android.injected.signing.key.alias' => ENV['KEY_ALIAS'],
        'android.injected.signing.key.password' => ENV['KEY_PASSWORD'],
      },
    )
  end

  desc 'Push a new build to the Google Play Store'
  lane :upload do
    upload_to_play_store(
      track: 'internal',
      version_name: ENV['RELEASE_NAME'],
      aab: './android/app/build/outputs/bundle/release/app-release.aab',
      json_key_data: Base64.decode64(ENV['GOOGLE_PLAY_KEY']),
      package_name: ENV['PACKAGE_NAME'],
      release_status: 'draft',
    )
  end
end
