name: 'Build App and Upload'

on:
  workflow_dispatch:
    inputs:
      buildPlatform:
        description: 'Platform to Build'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - ios
          - android

  release:
    types: [published]

jobs:
  build_ios:
    runs-on: macos-latest

    if: github.event_name == 'release' || inputs.buildPlatform == 'all' || inputs.buildPlatform == 'ios'

    steps:
      - name: List Xcode Installs
        run: sudo ls -1 /Applications | grep "Xcode"

      - name: Select Xcode 26.2
        run: sudo xcode-select -s /Applications/Xcode_26.2.app/Contents/Developer

      - name: Check Xcode Version
        run: /usr/bin/xcodebuild -version

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Fastlane
        run: |
          sudo gem install fastlane -NV
          fastlane --version

      - name: Install mise and dependencies
        uses: jdx/mise-action@v3

      - name: Install Dependencies
        run: pnpm install

      - name: Build Basemap
        run: pnpm pmtiles

      - name: Build Web Assets
        run: pnpm build

      - name: Capacitor Sync [iOS]
        run: pnpm exec cap sync ios

      - name: Fastlane Build [iOS]
        run: fastlane ios build
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_BASE64: ${{ secrets.ASC_KEY_BASE64 }}
          GIT_AUTHORIZATION: ${{ secrets.GIT_AUTHORIZATION }}
          CHANGELOG: ${{ github.event.release.body }}

  build_android:
    runs-on: ubuntu-latest

    if: github.event_name == 'release' || inputs.buildPlatform == 'all' || inputs.buildPlatform == 'android'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Fastlane
        run: |
          sudo gem install fastlane -NV
          fastlane --version

      - name: Install mise and dependencies
        uses: jdx/mise-action@v3

      - name: Install Dependencies
        run: pnpm install

      - name: Build Basemap
        run: pnpm pmtiles

      - name: Build Web Assets
        run: pnpm build

      - name: Capacitor Sync [Android]
        run: pnpm exec cap sync android

      - name: Decode Signing Keystore
        run: |
          echo "${{ secrets.AAB_SIGNING_KEY }}" | base64 --decode > "./android/app/maroon-rides-release-key.jks"

      - name: Fastlane Build [Android]
        run: fastlane android build
        env:
          KEY_ALIAS: ${{ secrets.AAB_KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.AAB_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.AAB_PASSWORD }}
          KEY_PATH: ${{ github.workspace }}/android/app/maroon-rides-release-key.jks

          GOOGLE_PLAY_KEY: ${{ secrets.GOOGLE_PLAY_KEY }}
          PACKAGE_NAME: 'com.maroonrides.maroonrides'

      - uses: actions/upload-artifact@v4
        with:
          name: app-bundle.aab
          path: ./android/app/build/outputs/bundle/release/app-release.aab

      - name: Set outputs
        id: git_sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Upload to Play Store [Android]
        run: fastlane android upload
        env:
          GOOGLE_PLAY_KEY: ${{ secrets.GOOGLE_PLAY_KEY }}
          RELEASE_NAME: ${{ github.event.release.tag_name || steps.git_sha.outputs.sha_short }}
          PACKAGE_NAME: 'com.maroonrides.maroonrides'
