name: Fix formatting

on:
  pull_request:
    types: [labeled]

permissions: {}

jobs:
  format:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'ci:format' }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies with mise
        uses: jdx/mise-action@v3
          
      - name: Install dependencies
        run: pnpm install

      - name: Lint with expo
        run: npx expo lint --fix

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'chore: fix formatting'

      - name: Remove label
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'ci:format'
            })
